[package]
name = "zcash-client"
version = "0.1.0"
authors = ["jczuchnowski <jakub.czuchnowski@gmail.com>"]

[dependencies]
base64 = "~0.9.1"
chrono = "0.4.2"
data-encoding = "2.1.1"
futures = "0.1.21"
hyper = "0.11.25"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
